export const videos = [
  {
    _id: "ejWo1KHRYTI",
    title: "Naruto 「AMV」- Legends Never Die | HD",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "More Than AMV",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRNJFeB6n6aybIux9vhIo-RaNaPHkvKnkMe-GKrTg=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "xylh_sJAYdc",
    title: "One Piece | The Greatest Story Ever Told「ASMV」",
    createdAt: "17 Jan 2022",
    views: "841,712",
    likes: "45k",
    creator: "SRA Music Videos",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLS-PPxyhkwbr95kI3EOGfGDhaLVS1K2yjFzGnAg=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "ZWXuGxQ5G_0",
    title: "[2022 Spring Anime] SPY×FAMILY - Main Trailer",
    createdAt: "18 Mar 2022",
    views: "347,897",
    likes: "20k",
    creator: "Muse Asia",
    creatorImg:
      "https://yt3.ggpht.com/xdgNgosFHeVJ8BNdypwReOje1Luer4O521yV1-k5lVWRuRdmHzq9kLsNz9eVLRBCewW56fP9CQ=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Trailer",
    subscriber: "200k",
  },
  {
    _id: "Z6wP5eMNykE",
    title: "The Strongest of All || Might Guy AMV",
    createdAt: "16 Oct 2020",
    views: "2,551,564",
    likes: "89k",
    creator: "Tributer Craft",
    creatorImg:
      "https://yt3.ggpht.com/ZdQI_KNU6hailRhhYFjBgnWDiOf5yL4p2EAKQGo4wgVF3CgwpexbwIr29QoiMitz5dXyTQ6LoQ=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "jHaBC7Ulkow",
    title: "Tokyo Revengers - Opening Theme [English Sub]",
    createdAt: "27 Dec 2015",
    views: "8,478,157",
    likes: "155k",
    creator: "Muse Asia",
    creatorImg:
      "https://yt3.ggpht.com/xdgNgosFHeVJ8BNdypwReOje1Luer4O521yV1-k5lVWRuRdmHzq9kLsNz9eVLRBCewW56fP9CQ=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Opening",
    subscriber: "200k",
  },
  {
    _id: "iutQJzAXiWo",
    title: "BLEACH: Thousand Year Blood War – Official Trailer",
    createdAt: "18 Aug 2021",
    views: "1,007,602",
    likes: "30k",
    creator: "JP Anime",
    creatorImg:
      "https://yt3.ggpht.com/ZCszwNVr6Nov8Ylcni-sMj9nWiHVWC-01NRlp9zPWfjrZ77p3iCaLgEmNxEe8668y17VK_h0JsU=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Trailer",
    subscriber: "200k",
  },
  {
    _id: "AgBUP8TJqV8",
    title: "Shingeki No Kyojin Opening 1",
    createdAt: "27 Dec 2015",
    views: "8,500,125",
    likes: "155k",
    creator: "Kimmeh",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQSJ6MTKxjI38xQs6_1XGi3A3RvdN7GnnUkPHmJPQ=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Opening",
    subscriber: "200k",
  },
  {
    _id: "BkaH3h7NCx4",
    title: "Shingeki No Kyojin - All Openings",
    createdAt: "9 Jan 2022",
    views: "1,873,017",
    likes: "125k",
    creator: "Anirun",
    creatorImg:
      "https://yt3.ggpht.com/HJFiMWYiq1H5yExW1XRP1HlIcguqwy2_ZVD_a_iRSdNRobrt2UsNWEDcV1s6Ne4ZrC2a20eE=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Opening",
    subscriber: "200k",
  },
  {
    _id: "oJwMiU3RJmA",
    title: "Naruto Shippuden OP / Opening 3",
    createdAt: "10 Jun 2020",
    views: "10,184,909",
    likes: "181k",
    creator: "SensenWorld",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQVWtlmTTxY50ubOwCkLvynzpKWFJMkfokoC8v_kg=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Opening",
    subscriber: "200k",
  },
  {
    _id: "S1uu7NWvu6k",
    title: "Dragon Ball Super Japanese Opening 1 (Chōzetsu☆Dynamic!)",
    createdAt: "12 Jul 2018",
    views: "2,428,941",
    likes: "42k",
    creator: "Dragon Ball Music Archive",
    creatorImg:
      "https://yt3.ggpht.com/7dEhAFZf-de8MiMG1ybcAoSTfAqhAh8_thdK22G3njruUH4GxZJQ_0jk9mAfJj6qTmAonDyM64o=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Opening",
    subscriber: "200k",
  },
  {
    _id: "6hp27JeCf4c",
    title: "[AMV/ASMV] Vegeta I Pride (Dragon Ball Super)",
    createdAt: "26 May 2020",
    views: "941,777",
    likes: "21k",
    creator: "Ikuzo Network",
    creatorImg:
      "https://yt3.ggpht.com/qBFYIHs3KMdD2ZEc9eItZpBynqV01zr3i-CN_RWXjjRMx4EKK4kMhSWwEROM0Cz939fgIc9zpg=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "7RUylQDHQMk",
    title: "Itachi Uchiha AMV - Impossible",
    createdAt: "2 Sept 2017",
    views: "39,743,018",
    likes: "511k",
    creator: "King AMV",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSEafFkbBFiWincFBx95ftecHVxTlmMX11yKXaakw=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "DPJjrArxwgc",
    title: "Ultra Instinct Goku vs Jiren - No Glory (Skan & Krale) [AMV]",
    createdAt: "8 May 2019",
    views: "555,141",
    likes: "8.1k",
    creator: "ChivalricPig",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRNoY63ZqFeh_TWeMFoOxIVFKE_dDbkVnanyBEj=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "XjvaJH8aRc0",
    title: "Demon Slayer: Kimetsu no Yaiba - OP Full Gurenge",
    createdAt: "24 Sept 2021",
    views: "16,589,801",
    likes: "178k",
    creator: "Anime OST",
    creatorImg:
      "https://yt3.ggpht.com/WXBe_uXHuD4IFIiUuEOu4mPqy7LUvgIbWDeMvD4mxPPW97gVSlCW2hnwFxub6Dj1RKyID-_v_w=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Opening",
    subscriber: "200k",
  },
  {
    _id: "7aMOurgDB-o",
    title: "Tokyo Ghoul – Opening Theme – Unravel",
    createdAt: "16 Jul 2014",
    views: "57,636,628",
    likes: "871k",
    creator: "Crunchyroll Dubs",
    creatorImg:
      "https://yt3.ggpht.com/-gXbJ-meZMyTkJA5A1WQa1PKEF8G-cLL0cTz02IlE13MfCtKg2xctLv_ZuId_ICjT3m0U_qW3A=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Opening",
    subscriber: "200k",
  },
  {
    _id: "WAoPeG1LU1g",
    title: "Linked Horizon - Shinzou wo Sasageyo! [Shingeki no Kyojin S2 OP]",
    createdAt: "11 Aug 2017",
    views: "52,349,803",
    likes: "761k",
    creator: "Cytharia",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSS0uNqYevvNpmAIG8e7Z7cDv3xJjN5W0md5rmgfw=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Opening",
    subscriber: "200k",
  },
  {
    _id: "eHZNKqdxJKo",
    title: "Conqueror's haki - One piece [AMV]",
    createdAt: "17 Jul 2020",
    views: "7,106",
    likes: "182",
    creator: "Gol D Roger",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSJKfdP2pVTnH0KfWkfRbUQV_CZ0YpeAxNQoXPd=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "WGMc7SxIZfU",
    title: "[AMV] Haikyuu!! - Unstoppable",
    createdAt: "17 Mar 2018",
    views: "8,433,148",
    likes: "180k",
    creator: "NekoAMVs",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSC7SNY7VEWAkRqSZjc9o4_F_yJHhfguNXs6fM5=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "fR5_orbIkTc",
    title: "Haikyu!! Complete Season 2 - Official Trailer",
    createdAt: "23 Mar 2018",
    views: "71,410",
    likes: "931",
    creator: "Madman Anime",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSPEPJy_pwy2hYmyyrxk4flGAqOfoCfnz_z9viZZg=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Trailer",
    subscriber: "200k",
  },
  {
    _id: "dwv65QSdXSU",
    title: "Jujutsu Kaisen「AMV」- beggin",
    createdAt: "18 Mar 2021",
    views: "19,927,510",
    likes: "352k",
    creator: "genkayedits悪い",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRQnUa-dmn_YOlo0k1SvJA7aDiIrn2-3BFbJPuejA=s88-c-k-c0x00ffffff-no-rj",
    category: "AMV",
    subscriber: "200k",
  },
  {
    _id: "FHgm89hKpXU",
    title: "Dragon Ball Super: Broly Movie Trailer",
    createdAt: "20 Jul 2018",
    views: "16,579,903",
    likes: "283k",
    creator: "IGN",
    creatorImg:
      "https://yt3.ggpht.com/H_---ano_f27DOCejDhUdBMtBcxcv32MoXmFKQc_mBcxYSH4HPZTGuBUdm7UgI5VlutMOVX2=s88-c-k-c0x00ffffff-no-rj",
    category: "Anime Trailer",
    subscriber: "200k",
  },
];
